export const mock_data = [
	{
		id: 1,
		name: "Emma",
		company: "Target",
		category: "Office",
		price: 7557,
		shipping: false,
		store: "Meedoo",
		color: "Goldenrod",
		featured: true,
		reviews: 28,
		info: "dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus",
		available: true,
		sku: "jv2Uvyn2",
		stars: 1,
	},
	{
		id: 2,
		name: "Hagen",
		company: "marcos",
		category: "Living Room",
		price: 2086,
		shipping: false,
		store: "Blogtag",
		color: "Violet",
		featured: true,
		reviews: 73,
		info: "ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet",
		available: true,
		sku: "IVLfcH",
		stars: 2,
	},
	{
		id: 3,
		name: "Doroteya",
		company: "liddy",
		category: "Kitchen",
		price: 28334,
		shipping: true,
		store: "Gabvine",
		color: "Orange",
		featured: false,
		reviews: 4,
		info: "ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia",
		available: true,
		sku: "U00Vbvnsx",
		stars: 5,
	},
	{
		id: 4,
		name: "Alison",
		company: "ikea",
		category: "Bedroom",
		price: 12159,
		shipping: true,
		store: "Thoughtstorm",
		color: "Pink",
		featured: false,
		reviews: 70,
		info: "vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor",
		available: false,
		sku: "p67pbE1y",
		stars: 1,
	},
	{
		id: 5,
		name: "Holmes",
		company: "muller",
		category: "Dining",
		price: 16090,
		shipping: false,
		store: "Edgeblab",
		color: "Maroon",
		featured: true,
		reviews: 86,
		info: "a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium",
		available: false,
		sku: "idyIkQaj",
		stars: 5,
	},
	{
		id: 6,
		name: "Idell",
		company: "Target",
		category: "Kids",
		price: 52500,
		shipping: true,
		store: "Goldenrod",
		color: "Maroon",
		featured: false,
		reviews: 87,
		info: "nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget",
		available: false,
		sku: "BnTblK5x",
		stars: 3,
	},
	{
		id: 7,
		name: "Marge",
		company: "marcos",
		category: "Office",
		price: 863,
		shipping: false,
		store: "Feedbug",
		color: "Violet",
		featured: true,
		reviews: 88,
		info: "porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes",
		available: true,
		sku: "pBfLWe7XnKg",
		stars: 5,
	},
	{
		id: 8,
		name: "Neville",
		company: "liddy",
		category: "Living Room",
		price: 199,
		shipping: false,
		store: "Realbuzz",
		color: "Orange",
		featured: true,
		reviews: 71,
		info: "rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna",
		available: true,
		sku: "65xP4FYlFLI",
		stars: 2,
	},
	{
		id: 9,
		name: "Zaccaria",
		company: "ikea",
		category: "Kitchen",
		price: 432,
		shipping: false,
		store: "Quaxo",
		color: "Pink",
		featured: true,
		reviews: 71,
		info: "vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean",
		available: true,
		sku: "5gfmZp",
		stars: 2,
	},
	{
		id: 10,
		name: "Storm",
		company: "muller",
		category: "Bedroom",
		price: 9763,
		shipping: true,
		store: "Demimbu",
		color: "Maroon",
		featured: false,
		reviews: 82,
		info: "sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque",
		available: false,
		sku: "XthNGL1h",
		stars: 3,
	},
	{
		id: 11,
		name: "Dedra",
		company: "Target",
		category: "Dining",
		price: 1962,
		shipping: false,
		store: "Goldenrod",
		color: "Goldenrod",
		featured: false,
		reviews: 83,
		info: "nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a",
		available: false,
		sku: "YUxGbQSyAqf",
		stars: 1,
	},
	{
		id: 12,
		name: "Whit",
		company: "marcos",
		category: "Kids",
		price: 810,
		shipping: true,
		store: "Voonix",
		color: "Violet",
		featured: false,
		reviews: 79,
		info: "maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti",
		available: true,
		sku: "7aPAVC",
		stars: 3,
	},
	{
		id: 13,
		name: "Samuel",
		company: "liddy",
		category: "Office",
		price: 991,
		shipping: true,
		store: "Yadel",
		color: "Orange",
		featured: true,
		reviews: 45,
		info: "in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam",
		available: true,
		sku: "P85AVOm",
		stars: 3,
	},
	{
		id: 14,
		name: "Jacinda",
		company: "ikea",
		category: "Living Room",
		price: 795,
		shipping: false,
		store: "Jaxspan",
		color: "Pink",
		featured: true,
		reviews: 25,
		info: "enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis",
		available: true,
		sku: "9g5uB2jPY5li",
		stars: 2,
	},
	{
		id: 15,
		name: "Everard",
		company: "muller",
		category: "Kitchen",
		price: 269,
		shipping: true,
		store: "Flashdog",
		color: "Maroon",
		featured: false,
		reviews: 95,
		info: "eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean",
		available: true,
		sku: "0NRfNE1R",
		stars: 1,
	},
	{
		id: 16,
		name: "Christel",
		company: "Target",
		category: "Bedroom",
		price: 888,
		shipping: false,
		store: "Omba",
		color: "Goldenrod",
		featured: true,
		reviews: 50,
		info: "scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia",
		available: true,
		sku: "ijdJANwVgL",
		stars: 4,
	},
	{
		id: 17,
		name: "Halette",
		company: "marcos",
		category: "Dining",
		price: 789,
		shipping: false,
		store: "Plambee",
		color: "Violet",
		featured: true,
		reviews: 68,
		info: "nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis",
		available: true,
		sku: "fazTGiTjcriJ",
		stars: 3,
	},
	{
		id: 18,
		name: "Pyotr",
		company: "liddy",
		category: "Kids",
		price: 633,
		shipping: false,
		store: "Browsetype",
		color: "Orange",
		featured: true,
		reviews: 65,
		info: "semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel",
		available: false,
		sku: "oQsqsXMRuR",
		stars: 4,
	},
	{
		id: 19,
		name: "Carley",
		company: "ikea",
		category: "Office",
		price: 850,
		shipping: true,
		store: "Miboo",
		color: "Pink",
		featured: true,
		reviews: 37,
		info: "odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin",
		available: true,
		sku: "1Q3Uhav",
		stars: 4,
	},
	{
		id: 20,
		name: "Lucita",
		company: "muller",
		category: "Living Room",
		price: 958,
		shipping: true,
		store: "Browsebug",
		color: "Maroon",
		featured: false,
		reviews: 52,
		info: "ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis",
		available: true,
		sku: "70BczdUYWu1O",
		stars: 3,
	},
];
